In [ ]:
# Categorical features

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("label_encoding2.csv")

In [3]:
df.head()

   Unnamed: 0 Dept   Age  Experience  Salary       Education
0           0   HR  32.0         9.0   40000  Under_Graduate
1           1   HR  33.0        12.0   48000          Master
2           2   IT  35.0        12.0   45000          Master
3           3   IT  36.0        12.0   46000        Graduate
4           4   HR  34.0        11.0   36000        Graduate

In [4]:
df=df.drop(["Unnamed: 0"],axis=1)

In [5]:
df.head()

  Dept   Age  Experience  Salary       Education
0   HR  32.0         9.0   40000  Under_Graduate
1   HR  33.0        12.0   48000          Master
2   IT  35.0        12.0   45000          Master
3   IT  36.0        12.0   46000        Graduate
4   HR  34.0        11.0   36000        Graduate

In [6]:
df.nunique()

Dept           4
Age           17
Experience     9
Salary        14
Education      3
dtype: int64

In [ ]:
"""Often in machine learning, we want to convert 
categorical variables into some type of numeric format that can be readily used by algorithms.

There are two common ways to convert categorical variables into numeric variables:
    1. Label Encoding: Assign each categorical value an integer 
    value based on alphabetical order.

    2. One Hot Encoding: Create new variables that take on 
    values 0 and 1 to represent the original categorical values."""

In [7]:
df1=df.copy()

In [ ]:
#.astype("category").cat.codes function will change the categorical variable to numerical

In [8]:
# applying the .astype("category").cat.codes   function on Education column
df1.Education=df1.Education.astype("category").cat.codes
df1.head()

  Dept   Age  Experience  Salary  Education
0   HR  32.0         9.0   40000          2
1   HR  33.0        12.0   48000          1
2   IT  35.0        12.0   45000          1
3   IT  36.0        12.0   46000          0
4   HR  34.0        11.0   36000          0

In [9]:
## applying the .astype("category").cat.codes   function on Department column
df1.Dept=df1.Dept.astype("category").cat.codes
df1.head()

   Dept   Age  Experience  Salary  Education
0     0  32.0         9.0   40000          2
1     0  33.0        12.0   48000          1
2     1  35.0        12.0   45000          1
3     1  36.0        12.0   46000          0
4     0  34.0        11.0   36000          0

In [ ]:
# after apply the .astype("category").cat.codes function... 
#we found the values has been assigned as per alphabet 0,1,2,3....20 as per requirement.
# as value 20 is much higher than 0, to avoid this problem another solution is as below:-

In [13]:
df2=df.copy()

In [14]:
df2.head()

  Dept   Age  Experience  Salary       Education
0   HR  32.0         9.0   40000  Under_Graduate
1   HR  33.0        12.0   48000          Master
2   IT  35.0        12.0   45000          Master
3   IT  36.0        12.0   46000        Graduate
4   HR  34.0        11.0   36000        Graduate

In [ ]:
# we can do apply the .get_dummies function all value will be assign 0 and 1 only

In [15]:
df2=pd.get_dummies(df2,columns=["Dept","Education"])

In [17]:
df2.head(10)

,Age,Experience,Salary,Dept_HR,Dept_IT,Dept_Marketing,Dept_Sales,Education_Graduate,Education_Master,Education_Under_Graduate
0,32.0,9.0,40000,1,0,0,0,0,0,1
1,33.0,12.0,48000,1,0,0,0,0,1,0
2,35.0,12.0,45000,0,1,0,0,0,1,0
3,36.0,12.0,46000,0,1,0,0,1,0,0
4,34.0,11.0,36000,1,0,0,0,1,0,0
5,33.0,13.0,42000,0,1,0,0,1,0,0
6,56.0,12.0,39000,0,0,1,0,0,1,0
7,32.0,10.0,42000,1,0,0,0,0,1,0
8,31.0,12.0,36000,0,0,1,0,0,0,1
9,45.0,14.0,45000,0,1,0,0,0,1,0

In [ ]:
# to avoide the Multi collinearity we should drop any one of the column ,
#which is not givng any new information for further training ,

In [18]:
df2=df2.drop(["Dept_HR"],axis=1)

In [19]:
df2=df2.drop(["Education_Graduate"],axis=1)

In [26]:
df2.head(20)

,Age,Experience,Salary,Dept_IT,Dept_Marketing,Dept_Sales,Education_Master,Education_Under_Graduate
0,32.000000,9.0,40000,0,0,0,0,1
1,33.000000,12.0,48000,0,0,0,1,0
2,35.000000,12.0,45000,1,0,0,1,0
3,36.000000,12.0,46000,1,0,0,0,0
4,34.000000,11.0,36000,0,0,0,0,0
5,33.000000,13.0,42000,1,0,0,0,0
6,56.000000,12.0,39000,0,1,0,1,0
7,32.000000,10.0,42000,0,0,0,1,0
8,31.000000,12.0,36000,0,1,0,0,1
9,45.000000,14.0,45000,1,0,0,1,0
10,50.000000,12.0,46000,0,0,1,1,0
11,75.000000,14.0,45500,0,0,0,0,0
12,29.000000,8.5,38000,0,0,0,0,0
13,32.000000,11.0,39000,0,0,0,0,1
14,38.000000,12.0,35000,0,0,1,1,0
15,37.272727,12.0,32000,0,0,0,0,1
16,42.000000,14.0,42000,1,0,0,0,0
17,50.000000,13.0,39000,0,1,0,1,0
18,38.000000,11.0,42000,0,0,0,0,0
19,20.000000,2.0,22000,0,0,0,0,1

In [ ]:
# correct label encoding means high education must assign high value 
#like PHd should have 3 , Master 2 Graduate 1 Under graduate should have 0
# we can do it by using Map and Dict creation.

In [23]:
df5=df.copy()

In [24]:
df5.head()

  Dept   Age  Experience  Salary       Education
0   HR  32.0         9.0   40000  Under_Graduate
1   HR  33.0        12.0   48000          Master
2   IT  35.0        12.0   45000          Master
3   IT  36.0        12.0   46000        Graduate
4   HR  34.0        11.0   36000        Graduate

In [25]:
# correct way of ordinal encoding 
df5["Education"]=df5["Education"].map({"Master":2,"Graduate":1,"Under_Graduate":0})
df5.head()

  Dept   Age  Experience  Salary  Education
0   HR  32.0         9.0   40000          0
1   HR  33.0        12.0   48000          2
2   IT  35.0        12.0   45000          2
3   IT  36.0        12.0   46000          1
4   HR  34.0        11.0   36000          1