In [ ]:
# population and sampling

In [1]:
import numpy as np

In [ ]:
# creating a dataset

In [2]:
import pandas as pd 
school={'ID':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],'NAME':["Mayank","Anu","Geeta","Ramesh","Prakash","Swati","Sweta",'Ravi','Raju',"Archana","Madhuri","Irfan","Sabina",'Alex','Rohan','Kiran','Jack',"Anjali","Alok","Preeti"],
         'MATH':[70,55,70,89,90,76,44,50,70,88,60,70,80,77,78,59,77,98,99,99],
         'ENGLISH':[71,90,70,55,60,70,78,98,67,87,78,79,45,76,33,76,79,78,78,99],'COMPUTER':[98,90,76,55,65,70,88,98,67,84,90,99,45,88,83,76,99,78,77,97],'AWARD':[0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1]}
df = pd.DataFrame(data=school)

In [3]:
df

    ID     NAME  MATH  ENGLISH  COMPUTER  AWARD
0    1   Mayank    70       71        98      0
1    2      Anu    55       90        90      1
2    3    Geeta    70       70        76      0
3    4   Ramesh    89       55        55      0
4    5  Prakash    90       60        65      0
5    6    Swati    76       70        70      0
6    7    Sweta    44       78        88      0
7    8     Ravi    50       98        98      1
8    9     Raju    70       67        67      0
9   10  Archana    88       87        84      1
10  11  Madhuri    60       78        90      0
11  12    Irfan    70       79        99      0
12  13   Sabina    80       45        45      0
13  14     Alex    77       76        88      0
14  15    Rohan    78       33        83      0
15  16    Kiran    59       76        76      0
16  17     Jack    77       79        99      0
17  18   Anjali    98       78        78      0
18  19     Alok    99       78        77      0
19  20   Preeti    99       99        97      1

In [4]:
df["AWARD"].value_counts()

0    16
1     4
Name: AWARD, dtype: int64

In [5]:
df.set_index("ID",inplace=True)
df

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
1    Mayank    70       71        98      0
2       Anu    55       90        90      1
3     Geeta    70       70        76      0
4    Ramesh    89       55        55      0
5   Prakash    90       60        65      0
6     Swati    76       70        70      0
7     Sweta    44       78        88      0
8      Ravi    50       98        98      1
9      Raju    70       67        67      0
10  Archana    88       87        84      1
11  Madhuri    60       78        90      0
12    Irfan    70       79        99      0
13   Sabina    80       45        45      0
14     Alex    77       76        88      0
15    Rohan    78       33        83      0
16    Kiran    59       76        76      0
17     Jack    77       79        99      0
18   Anjali    98       78        78      0
19     Alok    99       78        77      0
20   Preeti    99       99        97      1

In [8]:
sample1=df.sample()
sample1

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
5   Prakash    90       60        65      0

In [ ]:
df.sample(
    n=None,
    frac:  None,
    replace: False,
    weights=None,
    random_state=None,
    axis:False,
)

In [ ]:
# n is the no. of sample
#frac= fraction 10%   frac=0.1
#replace- replacement allowed , repetation allowed
#weight:-by default each observation is equally weighted. 
#we can assign weighted to individual observation.
#random_state:-reproduce the same sample

In [12]:
sample2=df.sample(frac=0.1)
sample2

      NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
18  Anjali    98       78        78      0
13  Sabina    80       45        45      0

In [23]:
sample3=df.sample(n=5)
sample3

      NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
4   Ramesh    89       55        55      0
9     Raju    70       67        67      0
15   Rohan    78       33        83      0
19    Alok    99       78        77      0
18  Anjali    98       78        78      0

In [20]:
sample3=df.sample(n=5,random_state=1)
sample3

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
4    Ramesh    89       55        55      0
17     Jack    77       79        99      0
7     Sweta    44       78        88      0
11  Madhuri    60       78        90      0
3     Geeta    70       70        76      0

In [24]:
sample4=df.sample(n=5,random_state=1)
sample4

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
4    Ramesh    89       55        55      0
17     Jack    77       79        99      0
7     Sweta    44       78        88      0
11  Madhuri    60       78        90      0
3     Geeta    70       70        76      0

In [25]:
sample5=df.sample(n=5,random_state=102)
sample5

      NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
2      Anu    55       90        90      1
6    Swati    76       70        70      0
18  Anjali    98       78        78      0
13  Sabina    80       45        45      0
4   Ramesh    89       55        55      0

In [26]:
sample6=df.sample(n=5,random_state=102)
sample6

      NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
2      Anu    55       90        90      1
6    Swati    76       70        70      0
18  Anjali    98       78        78      0
13  Sabina    80       45        45      0
4   Ramesh    89       55        55      0

In [27]:
sample6=df.sample(n=5,random_state=105,replace=True)
sample6

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
1    Mayank    70       71        98      0
10  Archana    88       87        84      1
5   Prakash    90       60        65      0
1    Mayank    70       71        98      0
1    Mayank    70       71        98      0

In [28]:
sample7=df.sample(n=5,random_state=105,replace=True)
sample7

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
1    Mayank    70       71        98      0
10  Archana    88       87        84      1
5   Prakash    90       60        65      0
1    Mayank    70       71        98      0
1    Mayank    70       71        98      0

In [29]:
sample8=df.sample(n=5,random_state=105,replace=False)
sample8

       NAME  MATH  ENGLISH  COMPUTER  AWARD
ID
3     Geeta    70       70        76      0
11  Madhuri    60       78        90      0
14     Alex    77       76        88      0
6     Swati    76       70        70      0
8      Ravi    50       98        98      1

In [30]:
df["AWARD"].value_counts()

0    16
1     4
Name: AWARD, dtype: int64