In [ ]:
# Jan_17_Bangalore Housing_Assignment

In [1]:
#Importing Important Libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib

In [2]:
# download the data set
df1=pd.read_csv("Bangalore_House.csv")
df1.head(100)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
95,Super built-up Area,Ready To Move,Domlur,3 BHK,NaN,1540,3.0,2.0,90.00
96,Plot Area,Ready To Move,Kengeri,4 Bedroom,Goardth,2894,4.0,1.0,245.00
97,Super built-up Area,Ready To Move,Sarjapura - Attibele Road,3 BHK,NaN,1330,2.0,1.0,48.00
98,Built-up Area,Ready To Move,Devasthanagalu,2 BHK,NaN,1200,2.0,1.0,65.00
99,Built-up Area,Ready To Move,T Dasarahalli,3 Bedroom,NaN,1200,3.0,1.0,90.00

In [3]:
df1.shape

(13320, 9)

In [4]:
df1.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
df1["area_type"].value_counts()

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64

In [7]:
# missing value
df1.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
df1["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [ ]:
# Bedroom can be replace with BHK

In [9]:
df1["size"]=df1["size"].str.replace("Bedroom","BHK")

In [10]:
df1["size"].unique()

array(['2 BHK', '4 BHK', '3 BHK', '6 BHK', '1 BHK', '1 RK', '8 BHK',
       '7 BHK', '5 BHK', '11 BHK', '9 BHK', nan, '27 BHK', '10 BHK',
       '19 BHK', '16 BHK', '43 BHK', '14 BHK', '12 BHK', '13 BHK',
       '18 BHK'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [13]:
encoder=LabelEncoder()
df1["area_type"]=encoder.fit_transform(df1["area_type"])
df1["location"]=encoder.fit_transform(df1["location"])
df1["size"]=encoder.fit_transform(df1["size"])

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  int32
 1   availability  13320 non-null  object
 2   location      13320 non-null  int32
 3   size          13320 non-null  int32
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), int32(3), object(3)
memory usage: 780.6+ KB

In [15]:
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,3,19-Dec,419,10,Coomee,1056,2.0,1.0,39.07
1,2,Ready To Move,317,13,Theanmp,2600,5.0,3.0,120.00
2,0,Ready To Move,1179,12,NaN,1440,2.0,3.0,62.00
3,3,Ready To Move,757,12,Soiewre,1521,3.0,1.0,95.00
4,3,Ready To Move,716,10,NaN,1200,2.0,1.0,51.00

In [16]:
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '2100 - 2850'

In [17]:
df1["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [18]:
df1["total_sqft"].head(100)

0     1056
1     2600
2     1440
3     1521
4     1200
      ...
95    1540
96    2894
97    1330
98    1200
99    1200
Name: total_sqft, Length: 100, dtype: object

In [19]:
df1["total_sqft"]=df1["total_sqft"].astype(str)

In [21]:
def sqft(x):
    y=x.split("-")
    if len(y)==2:
        return(float(y[0])+float(y[1]))/2
    elif len(y)==1:
        return x
    else:
        return None

In [23]:
df1["total_sqft"]=df1["total_sqft"].apply(sqft)

In [24]:
df1["total_sqft"].unique()

array(['1056', '2600', '1440', ..., 1258.5, '774', '4689'], dtype=object)

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  int32
 1   availability  13320 non-null  object
 2   location      13320 non-null  int32
 3   size          13320 non-null  int32
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), int32(3), object(3)
memory usage: 780.6+ KB

In [26]:
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '34.46Sq. Meter'

In [27]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Sq. Meter","")

C:\Users\User\AppData\Local\Temp/ipykernel_15620/2252966758.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df1["total_sqft"]=df1["total_sqft"].str.replace("Sq. Meter","")

In [28]:
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '4125Perch'

In [29]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Perch","")

In [30]:
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '1100Sq. Yards'

In [31]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Sq. Yards","")

C:\Users\User\AppData\Local\Temp/ipykernel_15620/1306217119.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df1["total_sqft"]=df1["total_sqft"].str.replace("Sq. Yards","")

In [32]:
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '5.31Acres'

In [33]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Acres","")
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '3Cents'

In [34]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Cents","")
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '24Guntha'

In [35]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Guntha","")
df1["total_sqft"]=df1["total_sqft"].astype(float)

ValueError: could not convert string to float: '1Grounds'

In [36]:
df1["total_sqft"]=df1["total_sqft"].str.replace("Grounds","")
df1["total_sqft"]=df1["total_sqft"].astype(float)

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  int32
 1   availability  13320 non-null  object
 2   location      13320 non-null  int32
 3   size          13320 non-null  int32
 4   society       7818 non-null   object
 5   total_sqft    13119 non-null  float64
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(4), int32(3), object(2)
memory usage: 780.6+ KB

In [38]:
df1["total_sqft"].fillna(df1["total_sqft"].median(),inplace=True)

In [39]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  int32
 1   availability  13320 non-null  object
 2   location      13320 non-null  int32
 3   size          13320 non-null  int32
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  float64
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(4), int32(3), object(2)
memory usage: 780.6+ KB

In [40]:
df2=df1.drop(["society"],axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  int32
 1   availability  13320 non-null  object
 2   location      13320 non-null  int32
 3   size          13320 non-null  int32
 4   total_sqft    13320 non-null  float64
 5   bath          13247 non-null  float64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
dtypes: float64(4), int32(3), object(1)
memory usage: 676.5+ KB

In [43]:
df2["bath"].fillna(df2["bath"].median(),inplace=True)

In [44]:
df2["balcony"].fillna(df2["balcony"].median(),inplace=True)

In [45]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  int32
 1   availability  13320 non-null  object
 2   location      13320 non-null  int32
 3   size          13320 non-null  int32
 4   total_sqft    13320 non-null  float64
 5   bath          13320 non-null  float64
 6   balcony       13320 non-null  float64
 7   price         13320 non-null  float64
dtypes: float64(4), int32(3), object(1)
memory usage: 676.5+ KB

In [46]:
df2["availability"].value_counts()

Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: availability, Length: 81, dtype: int64

In [48]:
df2.drop(["availability"],axis=1,inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   area_type   13320 non-null  int32
 1   location    13320 non-null  int32
 2   size        13320 non-null  int32
 3   total_sqft  13320 non-null  float64
 4   bath        13320 non-null  float64
 5   balcony     13320 non-null  float64
 6   price       13320 non-null  float64
dtypes: float64(4), int32(3)
memory usage: 572.5 KB

In [50]:
df2.head()

   area_type  location  size  total_sqft  bath  balcony   price
0          3       419    10      1056.0   2.0      1.0   39.07
1          2       317    13      2600.0   5.0      3.0  120.00
2          0      1179    12      1440.0   2.0      3.0   62.00
3          3       757    12      1521.0   3.0      1.0   95.00
4          3       716    10      1200.0   2.0      1.0   51.00

In [ ]:
#if we want we can create a new column for the Price per SQFT for the purpose of presentation

In [51]:
df3=df2.copy()

In [52]:
df3['price_per_sqft'] = df3['price']*100000 / df1['total_sqft']
# considering the given price is Rs. Lac we multiply it with 100000.
df3.head()

,area_type,location,size,total_sqft,bath,balcony,price,price_per_sqft
0,3,419,10,1056.0,2.0,1.0,39.07,3699.810606
1,2,317,13,2600.0,5.0,3.0,120.00,4615.384615
2,0,1179,12,1440.0,2.0,3.0,62.00,4305.555556
3,3,757,12,1521.0,3.0,1.0,95.00,6245.890861
4,3,716,10,1200.0,2.0,1.0,51.00,4250.000000